wordpress:
    image: blog.dotslash.tw-dev
    container_name: wordpress
    ports:
        - "8000:8080"
    links:
        - db

db:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wordpress
    ports:
      - '3306:3306'
    expose:
      - '3306'